
export const testData = [
  {
      email: "alicesmith89@gmail.com",
      firstName: "Alice",
      lastName: "Smith",
      country: "USA",
      city: "San Francisco",
      languages: ["English", "Spanish"],
      aboutYou: "Software engineer with a passion for blockchain. Worked on several DeFi projects.",
      currentPosition: "Software Engineer at Google",
      isUniversityStudent: false,
      githubHandle: "aliceSmith",
      discordHandle: "alice#1234",
      twitterHandle: "alice_smith",
      telegramHandle: "aliceSmith",
      interestedTracks: ["Finance & Payments", "Crypto Infrastructure"],
      yourRoles: ["Backend Developer", "Software Engineer"],
      yourSkills: ["Solidity", "Node.js", "PostgreSQL"],
      lookingToBuild: "A decentralized finance platform",
      rolesLookingFor: ["Frontend Developer", "Product Manager"],
      lookingForCollab: true
  },
  {
      email: "bjbiggs@gmail.com",
      firstName: "Bob",
      lastName: "Johnson",
      country: "Canada",
      city: "Toronto",
      languages: ["English", "French"],
      aboutYou: "I'm a game developer who loves to experiment with blockchain in gaming.",
      currentPosition: "Game Developer at Ubisoft",
      isUniversityStudent: false,
      githubHandle: "bobJ",
      discordHandle: "bobJ#5678",
      interestedTracks: ["Games & Entertainment"],
      yourRoles: ["Game Developer"],
      yourSkills: ["Unity", "C#"],
      lookingToBuild: "A blockchain-based multiplayer game",
      rolesLookingFor: ["AI / ML Engineer", "Backend Developer"],
      lookingForCollab: true
  },
  {
      email: "cj@startupx.com",
      firstName: "Charlie",
      lastName: "Brown",
      country: "UK",
      city: "London",
      languages: ["English"],
      aboutYou: "Product manager with a knack for turning ideas into reality.",
      currentPosition: "Product Manager at StartUpX",
      isUniversityStudent: false,
      twitterHandle: "charlieB",
      telegramHandle: "charlieB",
      interestedTracks: ["Mobile Consumer Apps", "DAOs & Network States"],
      yourRoles: ["Product Manager", "Business Development"],
      lookingToBuild: "A DAO for community projects",
      rolesLookingFor: ["Backend Developer", "Community Manager"],
      lookingForCollab: true
  },
  {
      email: "daisybear11@hotmail.com",
      firstName: "Daisy",
      lastName: "Miller",
      country: "Australia",
      city: "Sydney",
      languages: ["English"],
      aboutYou: "I'm a full-stack developer with a love for design.",
      currentPosition: "Freelancer",
      isUniversityStudent: true,
      githubHandle: "daisyM",
      discordHandle: "daisy#9101",
      interestedTracks: ["Artificial Intelligence", "Mobile Consumer Apps"],
      yourRoles: ["Full-stack Developer", "Visual Design"],
      yourSkills: ["React", "Node.js", "Tailwind CSS"],
      lookingToBuild: "AI-driven mobile app",
      rolesLookingFor: ["AI / ML Engineer"],
      lookingForCollab: true
  },
  {
      email: "ebwhits@gmail.com",
      firstName: "Ethan",
      lastName: "White",
      country: "India",
      city: "Mumbai",
      languages: ["English", "Hindi"],
      aboutYou: "Backend developer with a focus on scalable systems.",
      currentPosition: "Backend Developer at TechCorp",
      isUniversityStudent: false,
      githubHandle: "ethanW",
      interestedTracks: ["Crypto Infrastructure"],
      yourRoles: ["Backend Developer"],
      yourSkills: ["Java", "Spring Boot", "MySQL"],
      lookingToBuild: "Scalable crypto exchange",
      rolesLookingFor: ["Frontend Developer", "Finance"],
      lookingForCollab: true
  },
  {
      email: "charlotteswebb@gmail.com",
      firstName: "Fiona",
      lastName: "Green",
      country: "Germany",
      city: "Berlin",
      languages: ["German", "English"],
      aboutYou: "Marketing specialist with a keen interest in blockchain.",
      currentPosition: "Marketing Manager at ChainBuzz",
      isUniversityStudent: false,
      twitterHandle: "fionaG",
      interestedTracks: ["DAOs & Network States", "Finance & Payments"],
      yourRoles: ["Marketing"],
      lookingToBuild: "Blockchain marketing strategies",
      rolesLookingFor: ["Community Manager", "Content Creator"],
      lookingForCollab: true
  },
  {
      email: "georgesan.al@gmail.com",
      firstName: "George",
      lastName: "Harris",
      country: "Japan",
      city: "Tokyo",
      languages: ["Japanese", "English"],
      aboutYou: "Hardware engineer diving into the world of blockchain.",
      currentPosition: "Hardware Engineer at Electronix",
      isUniversityStudent: false,
      githubHandle: "georgeH",
      interestedTracks: ["Physical Infrastructure Networks"],
      yourRoles: ["Hardware Engineer"],
      yourSkills: ["Embedded C", "FPGA"],
      lookingToBuild: "Blockchain hardware solutions",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "hanbear18@aol.com",
      firstName: "Hannah",
      lastName: "Baker",
      country: "Brazil",
      city: "Sao Paulo",
      languages: ["Portuguese", "English"],
      aboutYou: "AI engineer with a passion for finance.",
      currentPosition: "AI Engineer at FinTechY",
      isUniversityStudent: true,
      githubHandle: "hannahB",
      interestedTracks: ["Artificial Intelligence", "Finance & Payments"],
      yourRoles: ["AI / ML Engineer"],
      yourSkills: ["Python", "TensorFlow", "PyTorch"],
      lookingToBuild: "AI-driven finance tools",
      rolesLookingFor: ["Backend Developer", "Finance"],
      lookingForCollab: true
  },
  {
      email: "digdig8@gmail.com",
      firstName: "Ivan",
      lastName: "Petrov",
      country: "Russia",
      city: "Moscow",
      languages: ["Russian", "English"],
      aboutYou: "Mobile developer with a love for crypto.",
      currentPosition: "Mobile Developer at AppMakers",
      isUniversityStudent: false,
      githubHandle: "ivanP",
      interestedTracks: ["Mobile Consumer Apps", "Crypto Infrastructure"],
      yourRoles: ["Mobile Developer"],
      yourSkills: ["Swift", "Kotlin", "React Native"],
      lookingToBuild: "Crypto wallet for mobile",
      rolesLookingFor: ["Backend Developer", "Product Design"],
      lookingForCollab: true
  },
  {
      email: "jlee3@gmail.com",
      firstName: "Jasmine",
      lastName: "Lee",
      country: "South Korea",
      city: "Seoul",
      languages: ["Korean", "English"],
      aboutYou: "Graphic designer with a passion for blockchain visuals.",
      currentPosition: "Graphic Designer at DesignHub",
      isUniversityStudent: true,
      discordHandle: "jasmineL#2345",
      interestedTracks: ["Games & Entertainment", "DAOs & Network States"],
      yourRoles: ["Graphic Design"],
      lookingToBuild: "Blockchain game assets",
      rolesLookingFor: ["Game Developer", "Content Creator"],
      lookingForCollab: true
  },
  {
    email: "liam.el.ob@gmail.com",
    firstName: "Liam",
    lastName: "O'Brien",
    country: "Ireland",
    city: "Cork",
    languages: ["English", "Irish"],
    aboutYou: "Blockchain enthusiast with a background in finance. I've been diving deep into the world of crypto for the past 7 years and am excited to bring my expertise to innovative projects.",
    currentPosition: "Financial Analyst at Deloitte",
    isUniversityStudent: false,
    githubHandle: "liamOB",
    twitterHandle: "liam_OB",
    interestedTracks: ['Finance & Payments', 'DAOs & Network States', 'Crypto Infrastructure'],
    yourRoles: ['Finance', 'Business Development'],
    yourSkills: [],
    lookingToBuild: "Decentralized finance analytics tool",
    rolesLookingFor: [],
    lookingForCollab: false
  },
  {
      email: "mia.leeA@aol.com",
      firstName: "Mia",
      lastName: "Rodriguez",
      country: "Argentina",
      city: "Buenos Aires",
      languages: ["Spanish"],
      aboutYou: "I'm a content creator with a passion for educating the masses about blockchain. Let's democratize knowledge!",
      currentPosition: "Content Creator at CryptoWorld",
      isUniversityStudent: true,
      discordHandle: "miaR#7890",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Content Creator'],
      yourSkills: [],
      lookingToBuild: "Blockchain educational series",
      rolesLookingFor: ['Graphic Design', 'Technical Writer'],
      lookingForCollab: true
  },
  {
      email: "selen7ech@gmail.com",
      firstName: "Noah",
      lastName: "Patel",
      country: "India",
      city: "Mumbai",
      languages: ["Hindi", "English"],
      aboutYou: "",
      currentPosition: "Student",
      isUniversityStudent: true,
      interestedTracks: ['Games & Entertainment'],
      yourRoles: [],
      yourSkills: [],
      lookingToBuild: "",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "daigol@kakao.com",
      firstName: "Olivia",
      lastName: "Kim",
      country: "South Korea",
      city: "Busan",
      languages: ["Korean", "English"],
      aboutYou: "Product designer with a love for sleek and user-friendly interfaces. Excited to design for the future of blockchain.",
      currentPosition: "Product Designer at Kakao",
      isUniversityStudent: false,
      telegramHandle: "oliviaKim",
      interestedTracks: ['Mobile Consumer Apps', 'Games & Entertainment'],
      yourRoles: ['Product Design', 'Visual Design'],
      yourSkills: ['Webflow', 'HTML/CSS'],
      lookingToBuild: "User-friendly crypto mobile app",
      rolesLookingFor: ['Frontend Developer', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "spidey.pj@gmail.com",
      firstName: "Parker",
      lastName: "Jones",
      country: "Australia",
      city: "Melbourne",
      languages: ["English"],
      aboutYou: "Backend developer with a focus on security and scalability. I believe in the power of decentralized systems.",
      currentPosition: "Backend Developer at Atlassian",
      isUniversityStudent: false,
      githubHandle: "parkerJ",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Backend Developer'],
      yourSkills: ['Node.js', 'PostgreSQL', 'Cryptography'],
      lookingToBuild: "Secure crypto exchange",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "qchiuliuu@aol.com",
      firstName: "Quinn",
      lastName: "Liu",
      country: "China",
      city: "Shanghai",
      languages: ["Chinese", "English"],
      aboutYou: "AI engineer with a passion for integrating machine learning with blockchain technologies.",
      currentPosition: "AI Engineer at Tencent",
      isUniversityStudent: false,
      githubHandle: "quinnL",
      interestedTracks: ['Artificial Intelligence'],
      yourRoles: ['AI / ML Engineer'],
      yourSkills: ['Python', 'TensorFlow', 'PyTorch'],
      lookingToBuild: "Decentralized AI training platform",
      rolesLookingFor: ['Backend Developer', 'Data Scientist'],
      lookingForCollab: true
  },
  {
      email: "riley@cryptohub.com",
      firstName: "Riley",
      lastName: "Smith",
      country: "Canada",
      city: "Vancouver",
      languages: ["English", "French"],
      aboutYou: "Community manager with a knack for building vibrant online communities. Let's bring people together!",
      currentPosition: "Community Manager at CryptoHub",
      isUniversityStudent: true,
      discordHandle: "rileyS#1235",
      interestedTracks: ['DAOs & Network States'],
      yourRoles: ['Community Manager'],
      yourSkills: [],
      lookingToBuild: "Online platform for crypto enthusiasts",
      rolesLookingFor: ['Frontend Developer', 'Content Creator'],
      lookingForCollab: true
  },
  {
      email: "smarti.188@hotmail.com",
      firstName: "Sam",
      lastName: "Martinez",
      country: "Mexico",
      city: "Guadalajara",
      languages: ["Spanish", "English"],
      aboutYou: "I'm a hardware engineer interested in the intersection of IoT and blockchain.",
      currentPosition: "Hardware Engineer at Qualcomm",
      isUniversityStudent: false,
      githubHandle: "samM",
      interestedTracks: ['Physical Infrastructure Networks'],
      yourRoles: ['Hardware Engineer'],
      yourSkills: ['Embedded C', 'FPGA'],
      lookingToBuild: "Blockchain-enabled IoT device",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "tbrownuk@gmail.com",
      firstName: "Taylor",
      lastName: "Brown",
      country: "UK",
      city: "Manchester",
      languages: ["English"],
      aboutYou: "Full-stack developer with a love for building scalable web applications. Exploring the world of blockchain.",
      currentPosition: "Full-stack Developer at CryptoTech",
      isUniversityStudent: false,
      githubHandle: "taylorB",
      interestedTracks: ['Mobile Consumer Apps', 'Crypto Infrastructure'],
      yourRoles: ['Full-stack Developer'],
      yourSkills: ['React', 'Node.js', 'MongoDB'],
      lookingToBuild: "Decentralized e-commerce platform",
      rolesLookingFor: ['Product Manager', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "ug8@chainlink.com",
      firstName: "Ulysses",
      lastName: "Garcia",
      country: "Chile",
      city: "Santiago",
      languages: ["Spanish"],
      aboutYou: "Marketing professional with a focus on the crypto space. Let's bring blockchain to the masses!",
      currentPosition: "Marketing Manager at ChainLink",
      isUniversityStudent: false,
      twitterHandle: "ulysses_G",
      interestedTracks: ['Finance & Payments', 'Crypto Infrastructure'],
      yourRoles: ['Marketing'],
      yourSkills: [],
      lookingToBuild: "Crypto marketing campaign",
      rolesLookingFor: ['Content Creator', 'Graphic Design'],
      lookingForCollab: true
  },
  {
      email: "vikki@daostack.net",
      firstName: "Victoria",
      lastName: "Nguyen",
      country: "Vietnam",
      city: "Ho Chi Minh City",
      languages: ["Vietnamese", "English"],
      aboutYou: "Passionate about the world of DAOs and network states. Let's build the future of governance together.",
      currentPosition: "Operations at DAOstack",
      isUniversityStudent: false,
      telegramHandle: "victoriaN",
      interestedTracks: ['DAOs & Network States'],
      yourRoles: ['Operations'],
      yourSkills: [],
      lookingToBuild: "DAO governance platform",
      rolesLookingFor: ['Backend Developer', 'Frontend Developer'],
      lookingForCollab: true
  },
  {
      email: "wzzz@aol.com",
      firstName: "William",
      lastName: "Zhang",
      country: "Singapore",
      city: "Singapore",
      languages: ["English", "Mandarin"],
      aboutYou: "Technical writer with a love for breaking down complex topics. Let's make blockchain understandable for everyone.",
      currentPosition: "Technical Writer at Ethereum Foundation",
      isUniversityStudent: true,
      githubHandle: "williamZ",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Technical Writer'],
      yourSkills: [],
      lookingToBuild: "Blockchain documentation platform",
      rolesLookingFor: ['Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "xantheman2@gmail.com",
      firstName: "Xander",
      lastName: "Jones",
      country: "New Zealand",
      city: "Wellington",
      languages: ["English"],
      aboutYou: "Game developer looking to integrate blockchain into immersive experiences.",
      currentPosition: "Game Developer at KiwiGames",
      isUniversityStudent: false,
      discordHandle: "xanderJ#4567",
      interestedTracks: ['Games & Entertainment'],
      yourRoles: ['Game Developer'],
      yourSkills: ['Unity', 'C#'],
      lookingToBuild: "Blockchain-based MMORPG",
      rolesLookingFor: ['AI / ML Engineer', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "yalitech@gmail.com",
      firstName: "Yasmine",
      lastName: "Ali",
      country: "Egypt",
      city: "Cairo",
      languages: ["Arabic", "English"],
      aboutYou: "Product manager with a focus on mobile consumer apps. Excited to explore blockchain solutions for mobile.",
      currentPosition: "Product Manager at MobileTech",
      isUniversityStudent: false,
      telegramHandle: "yasmineA",
      interestedTracks: ['Mobile Consumer Apps'],
      yourRoles: ['Product Manager'],
      yourSkills: [],
      lookingToBuild: "Crypto wallet for mobile",
      rolesLookingFor: ['Mobile Developer', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "zpatelitome@gmail.com",
      firstName: "Zane",
      lastName: "Patel",
      country: "India",
      city: "Delhi",
      languages: ["Hindi", "English"],
      aboutYou: "Backend developer with a passion for scalable and secure systems. Exploring the world of crypto infrastructure.",
      currentPosition: "Backend Developer at CryptoSolutions",
      isUniversityStudent: true,
      githubHandle: "zaneP",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Backend Developer'],
      yourSkills: ['Node.js', 'PostgreSQL', 'Cryptography'],
      lookingToBuild: "Decentralized identity platform",
      rolesLookingFor: ['Frontend Developer', 'AI / ML Engineer'],
      lookingForCollab: true
  },
  {
      email: "ariakhanyouseeme@aol.com",
      firstName: "Aria",
      lastName: "Khan",
      country: "Pakistan",
      city: "Karachi",
      languages: ["Urdu", "English"],
      aboutYou: "I'm a hardware engineer passionate about integrating blockchain into IoT devices.",
      currentPosition: "Hardware Engineer at TechSolutions",
      isUniversityStudent: false,
      githubHandle: "ariaK",
      interestedTracks: ['Physical Infrastructure Networks'],
      yourRoles: ['Hardware Engineer'],
      yourSkills: ['Embedded C', 'FPGA'],
      lookingToBuild: "Blockchain IoT gateway",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "blaketjr99@gmail.com",
      firstName: "Blake",
      lastName: "Rodriguez",
      country: "Costa Rica",
      city: "San Jose",
      languages: ["Spanish", "English"],
      aboutYou: "Community manager with a knack for building vibrant online communities. Let's bring people together in the world of DAOs!",
      currentPosition: "Community Manager at DAOspace",
      isUniversityStudent: true,
      discordHandle: "blakeR#7891",
      interestedTracks: ['DAOs & Network States'],
      yourRoles: ['Community Manager'],
      yourSkills: [],
      lookingToBuild: "Online platform for DAO enthusiasts",
      rolesLookingFor: ['Content Creator', 'Technical Writer'],
      lookingForCollab: true
  },
  {
    email: "perilous.carver@aol.com",
    firstName: "Caden",
    lastName: "Fernandez",
    country: "Spain",
    city: "Barcelona",
    languages: ["Spanish", "English"],
    aboutYou: "Blockchain developer with a focus on integrating AI solutions. I've been in the tech industry for over a decade and am excited about the future of decentralized AI.",
    currentPosition: "Blockchain Developer at TechSpan",
    isUniversityStudent: false,
    githubHandle: "cadenF",
    twitterHandle: "caden_F",
    interestedTracks: ['Artificial Intelligence', 'Crypto Infrastructure'],
    yourRoles: ['Backend Developer', 'AI / ML Engineer'],
    yourSkills: ['Solidity', 'Python', 'TensorFlow'],
    lookingToBuild: "A decentralized platform that allows for AI model training using blockchain for transparent and verifiable results.",
    rolesLookingFor: ['Data Scientist', 'Frontend Developer'],
    lookingForCollab: true
  },
  {
      email: "theblackdahl.one@gmail.com",
      firstName: "Dahlia",
      lastName: "Meyer",
      country: "Germany",
      city: "Berlin",
      languages: ["German", "English"],
      aboutYou: "I'm a passionate product designer with a love for creating intuitive user interfaces. Exploring how blockchain can enhance user experience.",
      currentPosition: "Product Designer at DesignHub",
      isUniversityStudent: true,
      discordHandle: "dahliaM#8910",
      interestedTracks: ['Mobile Consumer Apps', 'Games & Entertainment'],
      yourRoles: ['Product Design', 'Visual Design'],
      yourSkills: ['Webflow', 'HTML/CSS'],
      lookingToBuild: "A user-centric crypto wallet that simplifies the complexities of blockchain for everyday users.",
      rolesLookingFor: ['Frontend Developer', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "epetereson.ytk@gmail.com",
      firstName: "Elias",
      lastName: "Peterson",
      country: "Sweden",
      city: "Stockholm",
      languages: ["Swedish", "English"],
      aboutYou: "Technical writer with a mission to make blockchain accessible to everyone. I believe in the power of clear and concise documentation.",
      currentPosition: "Technical Writer at BlockDocs",
      isUniversityStudent: false,
      githubHandle: "eliasP",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Technical Writer'],
      yourSkills: [],
      lookingToBuild: "A comprehensive guide and documentation platform for various blockchain technologies, aiming to be the go-to resource for developers and enthusiasts alike.",
      rolesLookingFor: ['Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "fibrahi@cryptomena.com",
      firstName: "Faye",
      lastName: "Ibrahim",
      country: "Egypt",
      city: "Alexandria",
      languages: ["Arabic", "English"],
      aboutYou: "Marketing specialist in the crypto space. I've been helping projects gain visibility and traction in the MENA region.",
      currentPosition: "Marketing Specialist at CryptoMENA",
      isUniversityStudent: false,
      twitterHandle: "faye_I",
      interestedTracks: ['DAOs & Network States', 'Finance & Payments'],
      yourRoles: ['Marketing'],
      yourSkills: [],
      lookingToBuild: "A platform that bridges the gap between blockchain projects and the Arabic-speaking community, offering localized content and support.",
      rolesLookingFor: ['Content Creator', 'Community Manager'],
      lookingForCollab: true
  },
  {
      email: "gkwame@iotchain.com",
      firstName: "Gideon",
      lastName: "Kwame",
      country: "Ghana",
      city: "Accra",
      languages: ["English", "Twi"],
      aboutYou: "Hardware engineer with a focus on integrating blockchain solutions into everyday devices. I believe in the power of IoT combined with blockchain.",
      currentPosition: "Hardware Engineer at IoTChain",
      isUniversityStudent: true,
      githubHandle: "gideonK",
      interestedTracks: ['Physical Infrastructure Networks'],
      yourRoles: ['Hardware Engineer'],
      yourSkills: ['Embedded C', 'FPGA'],
      lookingToBuild: "A decentralized IoT network where devices can securely and transparently exchange data.",
      rolesLookingFor: ['Backend Developer', 'Network Engineer'],
      lookingForCollab: true
  },
  {
      email: "adropofhazel11@gmail.com",
      firstName: "Hazel",
      lastName: "Choi",
      country: "South Korea",
      city: "Daegu",
      languages: ["Korean", "English"],
      aboutYou: "I'm a full-stack developer with a passion for building scalable web applications. I've been exploring how blockchain can revolutionize the web.",
      currentPosition: "Full-stack Developer at WebChain",
      isUniversityStudent: false,
      githubHandle: "hazelC",
      interestedTracks: ['Mobile Consumer Apps', 'Crypto Infrastructure'],
      yourRoles: ['Full-stack Developer'],
      yourSkills: ['React', 'Node.js', 'MongoDB'],
      lookingToBuild: "A decentralized web hosting platform that gives users full control over their data and content.",
      rolesLookingFor: ['Backend Developer', 'Product Manager'],
      lookingForCollab: true
  },
  {
      email: "isilvah@chaincomm.com",
      firstName: "Isaiah",
      lastName: "Silva",
      country: "Brazil",
      city: "Rio de Janeiro",
      languages: ["Portuguese", "English"],
      aboutYou: "Community manager with a knack for building vibrant online communities. I've been managing online groups for various blockchain projects.",
      currentPosition: "Community Manager at ChainComm",
      isUniversityStudent: true,
      discordHandle: "isaiahS#4568",
      interestedTracks: ['DAOs & Network States'],
      yourRoles: ['Community Manager'],
      yourSkills: [],
      lookingToBuild: "An online platform that connects blockchain enthusiasts from around the world, fostering collaboration and innovation.",
      rolesLookingFor: ['Content Creator', 'Technical Writer'],
      lookingForCollab: true
  },
  {
      email: "jpo.dubois@gmail.com",
      firstName: "Jasmine",
      lastName: "Dubois",
      country: "France",
      city: "Paris",
      languages: ["French", "English"],
      aboutYou: "AI engineer with a passion for integrating machine learning with blockchain technologies. I believe in the power of decentralized AI.",
      currentPosition: "AI Engineer at AIChain",
      isUniversityStudent: false,
      githubHandle: "jasmineD",
      interestedTracks: ['Artificial Intelligence'],
      yourRoles: ['AI / ML Engineer'],
      yourSkills: ['Python', 'TensorFlow', 'PyTorch'],
      lookingToBuild: "A decentralized AI platform that allows for transparent and verifiable machine learning processes.",
      rolesLookingFor: ['Backend Developer', 'Data Scientist'],
      lookingForCollab: true
  },
  {
      email: "kingkaiLLG@gmail.com",
      firstName: "Kai",
      lastName: "Müller",
      country: "Germany",
      city: "Hamburg",
      languages: ["German", "English"],
      aboutYou: "Product manager with a focus on mobile consumer apps. I'm excited to explore how blockchain can enhance mobile experiences.",
      currentPosition: "Product Manager at AppChain",
      isUniversityStudent: true,
      telegramHandle: "kaiM",
      interestedTracks: ['Mobile Consumer Apps'],
      yourRoles: ['Product Manager'],
      yourSkills: [],
      lookingToBuild: "A mobile app that simplifies crypto trading and portfolio management for everyday users.",
      rolesLookingFor: ['Mobile Developer', 'Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "lgarcia@cryptotech.com",
      firstName: "Luna",
      lastName: "Garcia",
      country: "Mexico",
      city: "Monterrey",
      languages: ["Spanish", "English"],
      aboutYou: "Backend developer with a passion for building scalable and secure systems. I've been diving deep into the world of crypto infrastructure.",
      currentPosition: "Backend Developer at CryptoTech",
      isUniversityStudent: false,
      githubHandle: "lunaG",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Backend Developer'],
      yourSkills: ['Node.js', 'PostgreSQL', 'Cryptography'],
      lookingToBuild: "A decentralized identity platform that ensures user privacy and security.",
      rolesLookingFor: ['Frontend Developer', 'AI / ML Engineer'],
      lookingForCollab: true
  },
  {
      email: "mitojpn@gmail.com",
      firstName: "Mason",
      lastName: "Ito",
      country: "Japan",
      city: "Tokyo",
      languages: ["Japanese", "English"],
      aboutYou: "I'm a hardware engineer passionate about integrating blockchain into everyday devices. I believe in the power of IoT combined with blockchain.",
      currentPosition: "Hardware Engineer at IoTChain",
      isUniversityStudent: true,
      githubHandle: "masonI",
      interestedTracks: ['Physical Infrastructure Networks'],
      yourRoles: ['Hardware Engineer'],
      yourSkills: ['Embedded C', 'FPGA'],
      lookingToBuild: "A blockchain-powered IoT device that can securely and transparently exchange data with other devices.",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "ninska.19@aol.com",
      firstName: "Nina",
      lastName: "Kovalev",
      country: "Russia",
      city: "Moscow",
      languages: ["Russian", "English"],
      aboutYou: "Technical writer with a mission to make blockchain accessible to everyone. I've been writing documentation for various blockchain projects.",
      currentPosition: "Technical Writer at BlockDocs",
      isUniversityStudent: false,
      githubHandle: "ninaK",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Technical Writer'],
      yourSkills: [],
      lookingToBuild: "A comprehensive guide and documentation platform for the Solana blockchain, aiming to be the go-to resource for developers.",
      rolesLookingFor: ['Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "omart@webchain.com",
      firstName: "Oscar",
      lastName: "Martinez",
      country: "Mexico",
      city: "Cancun",
      languages: ["Spanish", "English"],
      aboutYou: "I'm a full-stack developer with a passion for building scalable web applications. I've been exploring the world of blockchain and am excited about its potential.",
      currentPosition: "Full-stack Developer at WebChain",
      isUniversityStudent: true,
      githubHandle: "oscarM",
      interestedTracks: ['Mobile Consumer Apps', 'Crypto Infrastructure'],
      yourRoles: ['Full-stack Developer'],
      yourSkills: ['React', 'Node.js', 'MongoDB'],
      lookingToBuild: "A decentralized social media platform that gives users full control over their data and content.",
      rolesLookingFor: ['Backend Developer', 'Product Manager'],
      lookingForCollab: true
  },
  {
      email: "pipedream19@gmail.com",
      firstName: "Piper",
      lastName: "Smith",
      country: "USA",
      city: "San Francisco",
      languages: ["English"],
      aboutYou: "Community manager with a knack for building vibrant online communities. I've been managing online groups for various blockchain projects in the Bay Area.",
      currentPosition: "Community Manager at ChainComm",
      isUniversityStudent: false,
      discordHandle: "piperS#4569",
      interestedTracks: ['DAOs & Network States'],
      yourRoles: ['Community Manager'],
      yourSkills: [],
      lookingToBuild: "An online platform that connects blockchain enthusiasts from the Bay Area, fostering local collaboration and innovation.",
      rolesLookingFor: ['Content Creator', 'Technical Writer'],
      lookingForCollab: true
  },
  {
      email: "quincydubois2@gmail.com",
      firstName: "Quincy",
      lastName: "Dubois",
      country: "France",
      city: "Lyon",
      languages: ["French", "English"],
      aboutYou: "AI engineer with a passion for integrating machine learning with blockchain technologies. I've been working on decentralized AI solutions for the past 5 years.",
      currentPosition: "AI Engineer at AIChain",
      isUniversityStudent: false,
      githubHandle: "quincyD",
      interestedTracks: ['Artificial Intelligence'],
      yourRoles: ['AI / ML Engineer'],
      yourSkills: ['Python', 'TensorFlow', 'PyTorch'],
      lookingToBuild: "A decentralized AI platform that offers transparent and verifiable machine learning processes, ensuring trust and reliability.",
      rolesLookingFor: ['Backend Developer', 'Data Scientist'],
      lookingForCollab: true
  },
  {
      email: "rito1@iotchain.com",
      firstName: "Riley",
      lastName: "Ito",
      country: "Japan",
      city: "Osaka",
      languages: ["Japanese", "English"],
      aboutYou: "I'm a hardware engineer passionate about the intersection of IoT and blockchain. I believe in the power of decentralized devices.",
      currentPosition: "Hardware Engineer at IoTChain",
      isUniversityStudent: true,
      githubHandle: "rileyI",
      interestedTracks: ['Physical Infrastructure Networks'],
      yourRoles: ['Hardware Engineer'],
      yourSkills: ['Embedded C', 'FPGA'],
      lookingToBuild: "A blockchain-powered IoT device that can securely and transparently exchange data in real-time.",
      rolesLookingFor: [],
      lookingForCollab: false
  },
  {
      email: "st.kovalevv@gmail.com",
      firstName: "Stella",
      lastName: "Kovalev",
      country: "Russia",
      city: "St. Petersburg",
      languages: ["Russian", "English"],
      aboutYou: "Technical writer with a focus on making blockchain accessible to everyone. I've been writing documentation for various blockchain projects and am excited about the future of decentralized tech.",
      currentPosition: "Technical Writer at BlockDocs",
      isUniversityStudent: false,
      githubHandle: "stellaK",
      interestedTracks: ['Crypto Infrastructure'],
      yourRoles: ['Technical Writer'],
      yourSkills: [],
      lookingToBuild: "A comprehensive guide and documentation platform for the Solana blockchain, aiming to be the go-to resource for both beginners and experts.",
      rolesLookingFor: ['Backend Developer'],
      lookingForCollab: true
  },
  {
      email: "tmartindeljo8@gmail.com",
      firstName: "Tristan",
      lastName: "Martinez",
      country: "Mexico",
      city: "Guadalajara",
      languages: ["Spanish", "English"],
      aboutYou: "I'm a full-stack developer with a love for building scalable web applications. I've been diving deep into the world of blockchain and am excited about its potential.",
      currentPosition: "Full-stack Developer at WebChain",
      isUniversityStudent: true,
      githubHandle: "tristanM",
      interestedTracks: ['Mobile Consumer Apps', 'Crypto Infrastructure'],
      yourRoles: ['Full-stack Developer'],
      yourSkills: ['React', 'Node.js', 'MongoDB'],
      lookingToBuild: "A decentralized e-commerce platform that offers users full control over their data and transactions.",
      rolesLookingFor: ['Backend Developer', 'Product Manager'],
      lookingForCollab: true
  }
];
